name: Build Akamai Edgegrid Tester
run-name: Build Akamai Edgegrid Tester
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GO_VERSION: "1.23.2"

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5go
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get .
      - name: Create output directory
        run: mkdir -p dist
      - name: Build for macOS (AMD64)
        run: go build -v -o dist/akamai-edgegrid-tester_${{ env.GOOS }}_${{ env.GOARCH }}
        env:
          GOOS: darwin
          GOARCH: amd64
      - name: Build for macOS (ARM64)
        run: go build -v -o dist/akamai-edgegrid-tester_${{ env.GOOS }}_${{ env.GOARCH }}
        env:
          GOOS: darwin
          GOARCH: armd64
      - name: Build for Linux (AMD64)
        run: go build -v -o dist/akamai-edgegrid-tester_${{ env.GOOS }}_${{ env.GOARCH }}
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Build for Linux (ARM64)
        run: go build -v -o dist/akamai-edgegrid-tester_${{ env.GOOS }}_${{ env.GOARCH }}
        env:
          GOOS: linux
          GOARCH: armd64
      - name: Build for Windows (AMD64)
        run: go build -v -o dist/akamai-edgegrid-tester_${{ env.GOOS }}_${{ env.GOARCH }}
        env:
          GOOS: windows
          GOARCH: amd64
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist/akamai-edgegrid-tester*

